apiVersion: mellanox.com/v1alpha1
kind: NicClusterPolicy
metadata:
   name: nic-cluster-policy
spec:
   sriovDevicePlugin:
     image: sriov-network-device-plugin
     repository: ghcr.io/k8snetworkplumbingwg
     version: v3.9.0
     imagePullSecrets: []
     config: |
       {
         "resourceList": [
           {
             "resourcePrefix": "nvidia.com",
             "resourceName": "hostdev",
             "selectors": {
               "vendors": ["15b3"],
               "devices": ["101a"],
               "drivers": [],
               "pfNames": [],
               "pciAddresses": [],
               "rootDevices": [],
               "linkTypes": [],
               "isRdma": true
             }
           }
         ]
       }
   secondaryNetwork:
     cniPlugins:
       image: plugins
       repository: ghcr.io/k8snetworkplumbingwg
       version: v1.5.0
       imagePullSecrets: []
     multus:
       image: multus-cni
       repository: ghcr.io/k8snetworkplumbingwg
       version: v4.1.0
       imagePullSecrets: []
     ipamPlugin:
       image: whereabouts
       repository: ghcr.io/k8snetworkplumbingwg
       version: v0.7.0
       imagePullSecrets: []