apiVersion: batch/v1
kind: Job
metadata:
  name: parallel
  labels:
    chapter: jobs
spec:
  parallelism: 1
  completions: 2000
  template:
    metadata:
      labels:
        chapter: jobs
    spec:
      containers:
      - name: fiber-pi-estimation
        image: calio/fiber-pi-estimation:latest
        imagePullPolicy: Always
      restartPolicy: OnFailure
