apiVersion: amd.com/v1alpha1
kind: DeviceConfig
metadata:
  name: bm.gpu.mi300x.8
  # use the namespace where AMD GPU Operator is running
  namespace: amd-gpu-operator
spec:
  driver:
    # disable the installation of our-of-tree amdgpu kernel module
    enable: false

  devicePlugin:
    devicePluginImage: rocm/k8s-device-plugin:latest
    nodeLabellerImage: rocm/k8s-device-plugin:labeller-latest

  # Specify the metrics exporter config
  metricsExporter:
    enable: true
    prometheus:
      serviceMonitor:
        enable: true
        interval: "60s" # Scrape frequency
        attachMetadata:
          node: true
        honorLabels: false
        honorTimestamps: true
        labels:
          release: kube-prometheus-stack # Prometheus release label for target discovery
        relabelings:
          - sourceLabels: [__meta_kubernetes_pod_node_name]
            separator: ;
            regex: ^(.*)$
            targetLabel: hostname
            replacement: $1
            action: replace
          - sourceLabels: [__meta_kubernetes_node_provider_id]
            targetLabel: instance_id
            action: replace
          - sourceLabels: [__meta_kubernetes_node_label_oci_oraclecloud_com_host_serial_number]
            targetLabel: host_serial_number
            action: replace
          - sourceLabels: [__meta_kubernetes_node_label_node_kubernetes_io_instance_type]
            targetLabel: instance_shape
            action: replace
          - sourceLabels: [__meta_kubernetes_node_label_oci_oraclecloud_com_rdma_cluster_id]
            targetLabel: cluster_name
            action: replace
          - sourceLabels: [pod]
            targetLabel: exporter_pod
            action: replace
            regex: (.*)
            replacement: $1
            # Drop the Prometheus-added 'pod' label to avoid conflict
          - action: labeldrop
            regex: pod

  testRunner:
    # To enable/disable the test runner, disabled by default
    enable: true

    # image for the test runner container
    image: docker.io/rocm/test-runner:v1.3.0-beta.0

    # specify the mount for test logs
    logsLocation:
      # mount path inside test runner container
      mountPath: "/var/log/amd-test-runner"

      # host path to be mounted into test runner container
      hostPath: "/var/log/amd-test-runner"

  # Specifythe node to be managed by this DeviceConfig Custom Resource
  selector:
    node.kubernetes.io/instance-type: "BM.GPU.MI300X.8"
