---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: npd-taint
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: npd-taint
  template:
    metadata:
      labels:
        app: npd-taint
    spec:
      serviceAccountName: npd-taint
      terminationGracePeriodSeconds: 1
      tolerations: [{ operator: "Exists" }]
      hostNetwork: true
      # GPU-only nodes (NVIDIA or AMD)
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu
                    operator: In
                    values: ["true"]
              - matchExpressions:
                  - key: amd.com/gpu
                    operator: In
                    values: ["true"]
      volumes:
        - { name: bin, emptyDir: {} }
        - { name: root, hostPath: { path: "/" } }
        - { name: dev, hostPath: { path: "/dev" } }
      initContainers:
        - name: kubectl-jq
          image: aga.ocir.io/hpc_limited_availability/oke/kubectl:latest
          imagePullPolicy: Always
          command: ["bash", "-c", "cp -v /usr/local/bin/{jq,kubectl} /mnt/"]
          volumeMounts: [{ name: bin, mountPath: /mnt }]
      containers:
        - name: npd-taint
          image: oraclelinux:9-slim
          command: ["/bin/bash"]
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - { name: root, mountPath: /host }
            - { name: bin, mountPath: /b }
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          args:
            - "-ec"
            - |
              while :; do
                NODES_WITH_ISSUES=$(/b/kubectl get nodes -o json | /b/jq -r '.items[]
                  | select (.metadata.labels."nvidia.com/gpu" == "true" or .metadata.labels."amd.com/gpu" == "true")
                  | { name: .metadata.name, error: .status.conditions[]
                    | select(.reason | test("^(Gpu|Rdma|Oca).*HasIssues$")) | .message }
                  | .name' | awk '{ print $1 }')

                if [ -n "$NODES_WITH_ISSUES" ]; then
                  /b/kubectl taint nodes $NODES_WITH_ISSUES "npd=node_has_issues:NoSchedule" --overwrite \
                    || echo "Failed to taint" >&2
                else
                  echo "No nodes with issues detected."
                fi

                sleep 60
              done
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
