apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: nvidia.com/mlnxnics
  name: example-sriov-network-nv-ipam-ippool-2
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "name": "example-sriov-network-nv-ipam-ippool-2",
      "plugins": [
        {
          "type": "sriov",
          "spoofchk": "off",
          "ipam": {
            "type": "nv-ipam",
            "poolName": "my-pool"
          }
        },
        { "type": "tuning",
          "sysctl": {
            "net.ipv4.conf.all.arp_announce": "2",
            "net.ipv4.conf.all.arp_filter": "1",
            "net.ipv4.conf.all.arp_ignore": "1",
            "net.ipv4.conf.all.rp_filter": "0",
            "net.ipv4.conf.all.accept_local": "1"
          },
          "mtu": 4220
        },
        { "type": "sbr" }
      ]
    }