apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: "example-sriov-network"
  namespace: nvidia-network-operator
spec:
  vlan: 0
  networkNamespace: "default"
  resourceName: "mlnxnics"
  ipam: |-
    {
      "type": "nv-ipam",
      "poolName": "my-pool"
    }
