apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-problem-detector
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: npd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-problem-detector
subjects:
  - kind: ServiceAccount
    name: node-problem-detector
    namespace: kube-system

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    app: node-problem-detector
spec:
  selector:
    matchLabels:
      app: node-problem-detector
  template:
    metadata:
      labels:
        app: node-problem-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.kubernetes.io/instance-type
                    operator: In
                    values:
                    - BM.GPU.A100-v2.8
                    - BM.GPU.B4.8
                    - BM.GPU4.8
                    - BM.GPU.H100.8
                    - BM.GPU.MI300X.8
      containers:
      - name: node-problem-detector
        command:
        - /node-problem-detector
        - --logtostderr
        - --config.system-log-monitor=/config/kernel-monitor.json,/config/readonly-monitor.json,/config/docker-monitor.json
        - --config.custom-plugin-monitor=/config/oke-gpu-healthcheck.json
        image: registry.k8s.io/node-problem-detector/node-problem-detector:v0.8.19
        resources:
          limits:
            cpu: 2
            memory: 2000Mi
          requests:
            cpu: 200m
            memory: 200Mi
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: root
          mountPath: /host
        - name: log
          mountPath: /var/log
          readOnly: true
        - name: kmsg
          mountPath: /dev/kmsg
          readOnly: true
        # Make sure node problem detector is in the same timezone
        # with the host.
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        - name: config
          mountPath: /config
          readOnly: true
        - mountPath: /etc/machine-id
          name: machine-id
          readOnly: true
        - mountPath: /run/systemd/system
          name: systemd
        - mountPath: /var/run/dbus/
          name: dbus
          mountPropagation: Bidirectional
      serviceAccountName: node-problem-detector
      volumes:
      - name: root
        hostPath:
          path: /
      - name: log
        # Config `log` to your system log directory
        hostPath:
          path: /var/log/
      - name: kmsg
        hostPath:
          path: /dev/kmsg
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config
        configMap:
          name: node-problem-detector-config
          defaultMode: 0777
          items:
          - key: kernel-monitor.json
            path: kernel-monitor.json
          - key: readonly-monitor.json
            path: readonly-monitor.json
          - key: docker-monitor.json
            path: docker-monitor.json
          - key: oke-gpu-healthcheck.json
            path: oke-gpu-healthcheck.json
          - key: check_nvidia_gpu_setup.py
            path: plugin/check_nvidia_gpu_setup.py
          - key: check_amd_gpu_setup.py
            path: plugin/check_amd_gpu_setup.py
          - key: rdma_link_flapping.py
            path: plugin/rdma_link_flapping.py
          - key: shared_logging.py
            path: plugin/shared_logging.py
          - key: xid_checker.py
            path: plugin/xid_checker.py
          - key: oke-healthchecks.sh
            path: plugin/oke-healthchecks.sh
      - name: machine-id
        hostPath:
          path: /etc/machine-id
          type: "File"
      - name: systemd
        hostPath:
          path: /run/systemd/system/
          type: ""
      - name: dbus
        hostPath:
          path: /var/run/dbus/
          type: ""
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
